### ISSUE TITLE
Unwanted export

### ISSUE THREAD

**Issue by elevenpassin** [aravindballa/node-gister#3]
https://github.com/aravindballa/node-gister/blob/57c727b7ccdd593136f1e86dfa1793bbeafa7075/src/logic.js#L16

I don't think you want to export this function. Is there any reason behind providing this function?

**Comment by aravindballa** [comment]
Ah, nice catch! I did that to use that function in `login.test.js`

**Comment by M-ZubairAhmed** [comment]
Shouldnt this issue be closed. i see it got merged
